// ELEMENT OF THE PAYROLL_SYSTEM PROGRAM
package payroll_system;

// ENUM CLASS TO STORE SPECIFIC DATA
public enum Department 
{
    PRODUCTION,MARKETING,FINANCE,HUMAN_RESOURCE,IT_SERVICES;
}
