// ELEMENT OF THE PAYROLL_SYSTEM PROGRAM
package payroll_system;

// ENUM CLASS TO STORE SPECIFIC DATA
public enum Job_title 
{
    OFFICE_WORKER,OFFICER,SUPERVISOR,TEAM_LEADER,MANAGER,CEO,DIRECTOR,SOFTWARE_ENGINNER,SOFTWARE_DEVELOPER,
    JUNIOR_SOFTWARE_DEVELOPER,JUNIOR_SOFTWARE_ENGINNER,CODER,PROGRAMMER_ANALYST; 
}
